name: Run test on pull request

on:
  pull_request:
    types:
      - labeled

jobs:
  runs-on: ubuntu-latest
  steps:
    run-test:
      if: ${{github.event.label.name == 'Run tests'}}
      runs-on: ubuntu-latest
      steps:
        - name: ${{matrix.platform}} ${{matrix.os}} ${{github.base_ref}}
          run: echo "All test passed"